# Use the official AWS Lambda Python runtime as a base
FROM public.ecr.aws/lambda/python:3.9-x86_64

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies 
RUN pip install --no-cache-dir -r requirements.txt -t "${LAMBDA_TASK_ROOT}"

# Copy the Lambda function code to the container
COPY lambda_function.py "${LAMBDA_TASK_ROOT}"

# Copy your lambda code and additional files
COPY . "${LAMBDA_TASK_ROOT}"

# Set the AWS_REGION environment variable
ENV AWS_REGION=us-east-1

# Set the command to run when the container starts.
CMD ["lambda_function.lambda_handler"] 